package wang.junqin.chaexpress.utils.DAO;

import java.io.Serializable;

import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.apihint.Internal;

/**
 * Created by KN on 2017/6/2.
 */

@Entity
public class ExpressEntity{

    @Id(assignable = true)
    private long id;


    private String expNum;

    private String expCom;

    private String expInfo;

    private long dateAdded;

    private String status;

    private String remark;

    @Generated(1720651114)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public ExpressEntity(long id, String expNum, String expCom, String expInfo,
            long dateAdded, String status, String remark) {
        this.id = id;
        this.expNum = expNum;
        this.expCom = expCom;
        this.expInfo = expInfo;
        this.dateAdded = dateAdded;
        this.status = status;
        this.remark = remark;
    }

    @Generated(296325710)
    public ExpressEntity() {
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getExpNum() {
        return expNum;
    }

    public void setExpNum(String expNum) {
        this.expNum = expNum;
    }

    public String getExpCom() {
        return expCom;
    }

    public void setExpCom(String expCom) {
        this.expCom = expCom;
    }

    public String getExpInfo() {
        return expInfo;
    }

    public void setExpInfo(String expInfo) {
        this.expInfo = expInfo;
    }

    public long getDateAdded() {
        return dateAdded;
    }

    public void setDateAdded(long dateAdded) {
        this.dateAdded = dateAdded;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    
}
